timer.Remove("HintSystem_OpeningMenu")
timer.Remove("HintSystem_Annoy1")
timer.Remove("HintSystem_Annoy2")

luna.Aurebesh = luna.Font("Aurebesh@18")

luna.LunaMontMini = luna.Font("Mont Bold@16")
luna.LunaMontMenuMiniFont = luna.Font("Mont Bold@" .. math.max(ScreenScale(4), 18), "weight:300")
luna.LunaMontNoticeFont = luna.Font("Mont Bold@" .. math.max(ScreenScale(8), 14), "weight:100 antialias:true")

luna.MontBase = luna.Font("Mont Bold@31")
luna.MontBase12 = luna.Font("Mont Bold@9")
luna.MontBase18 = luna.Font("Mont Bold@15", "weight:500")
luna.MontBase22 = luna.Font("Mont Bold@18", "weight:500")
luna.MontBase24 = luna.Font("Mont Bold@20")
luna.MontBase30 = luna.Font("Mont Bold@27")
luna.MontBase45 = luna.Font("Mont Bold@42", "weight:100")
luna.MontBase54 = luna.Font("Mont Bold@49")
luna.MontBase544 = luna.Font("Mont Bold@47")
luna.MontBase84 = luna.Font("Mont Bold@80")
luna.MontBaseBig = luna.Font("Mont Bold@78", "weight:500")
luna.MontBaseBigS = luna.Font("Mont Bold@78", "blursize:5 weight:500")
luna.MontBaseHud = luna.Font("Mont Bold@23")
luna.MontBaseLarge = luna.Font("Mont Bold@90", "weight:500")
luna.MontBaseLargeS = luna.Font("Mont Bold@" .. ScreenScale(50), "weight:500")
luna.MontBaseNormal = luna.Font("Mont Bold@50")
luna.MontBaseRotate = luna.Font("Mont Bold@34")
luna.MontBaseSmall = luna.Font("Mont Bold@10", "weight:300")
luna.MontBaseTitle = luna.Font("Mont Bold@34")
luna.MontBaseWarning = luna.Font("Mont Bold@17")

luna.MontBlack28 = luna.Font("Mont Black@25")
luna.MontBlack38 = luna.Font("Mont Black@33")
luna.MontBlack50 = luna.Font("Mont Black@55")

-- luna.MontBase24Wadik = luna.Font("Wadik@24", "weight:500")
-- luna.MontBase34Wadik = luna.Font("Wadik@34", "weight:500")

luna.NPC1 = luna.Font("Mont Black@60", "weight:100")
luna.NPC1Hit = luna.Font("Mont Bold@60", "weight:100")
luna.NPC1Neon = luna.Font("Mont Black@60", "blursize:6 weight:100")
luna.NPC2 = luna.Font("Mont Bold@46", "weight:100")
luna.NPC2Hit = luna.Font("Mont Bold@46", "weight:100")

luna.Notify = luna.Font("Mont Bold@18", "weight:500")

luna.Roboto15 = luna.Font("Mont Bold@15", "weight:100")
luna.Roboto21 = luna.Font("Mont Bold@21", "weight:100")
luna.Roboto24 = luna.Font("Mont Bold@24", "weight:100")

luna.MontHUDPrimary = luna.Font("Mont Bold@72", "weight:500")

luna.SquadSystemCommandsSubTitle = luna.Font("Mont Bold@" .. ScrH() * .02)
luna.SquadSystemCommandsTitle = luna.Font("Mont Black@" .. ScrH() * .06)
luna.SquadSystemCreateHint = luna.Font("Mont Bold@" .. ScrH() * .02)
luna.SquadSystemInviteText = luna.Font("Mont Bold@" .. ScrH() * .06)
luna.SquadSystemInviteTitle = luna.Font("Mont Black@" .. ScrH() * .07)
luna.SquadSystemListDetails = luna.Font("Mont Bold@" .. ScrH() * .02)
luna.SquadSystemListSQTitle = luna.Font("Mont Bold@" .. ScrH() * .025)
luna.SquadSystemOverHead = luna.Font("Mont Bold@" .. ScrH() * .02)
luna.SquadSystemPing = luna.Font("Mont Bold@15", "antialias:true additive:false")
luna.SquadSystemPingSmall = luna.Font("Mont Bold@12", "antialias:true additive:false")
luna.SquadSystemSideboardContext = luna.Font("Mont Bold@" .. ScrH() * .018)
luna.SquadSystemSideboardPlayerDetails = luna.Font("Mont Bold@" .. ScrH() * .015)
luna.SquadSystemSideboardPlayerName = luna.Font("Mont Bold@" .. ScrH() * .02)
luna.SquadSystemSideboardTitle = luna.Font("Mont Bold@" .. ScrH() * .035)

surface.CreateFont( "luna.MontBase24Markup", {font = "Mont Bold",size = 23,extended = true,})

TEAM_CONNECTING = team.SetUp(0, "Подключается...", Color(105,126,141))
TEAM_UNASSIGNED = team.SetUp(1001, "Не определен", Color(105,126,141))
TEAM_SPECTATOR = team.SetUp(1002, "Наблюдатель", Color(105,126,141))