--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher

local function AddPlayerModel(name, model)
	list.Set("PlayerOptionsModel", name, model)
	player_manager.AddValidModel(name, model)
end

--кастом
hook.Add('Think', 'luna_cont/lua/autorun/ct_pm.lua', function()
	hook.Remove('Think', 'luna_cont/lua/autorun/ct_pm.lua')
	AddPlayerModel("1", "models/sup/vrpm/trp/trp.mdl")
	AddPlayerModel("2", "models/sup/vrpm/para/para.mdl")
	AddPlayerModel("3", "models/sup/vrpm/scout/scout.mdl")
	AddPlayerModel("4", "models/sup/vrpm/med/med.mdl")
	AddPlayerModel("5", "models/sup/vrpm/eng/eng.mdl")
	AddPlayerModel("6", "models/sup/vrpm/assault/assault.mdl")
	AddPlayerModel("7", "models/sup/vrpm/arf/arf.mdl")
	AddPlayerModel("9", "models/sup/vrpm/1/trp/trp.mdl")
	AddPlayerModel("10", "models/sup/vrpm/1/sgt/sgt.mdl")
	AddPlayerModel("11", "models/sup/vrpm/1/ofc/ofc.mdl")
	AddPlayerModel("12", "models/sup/vrpm/104/arf/arf.mdl")
	AddPlayerModel("13", "models/sup/vrpm/104/cmd/cmd.mdl")
	AddPlayerModel("14", "models/sup/vrpm/104/dcmd/dcmd.mdl")
	AddPlayerModel("15", "models/sup/vrpm/104/desant/desant.mdl")
	AddPlayerModel("16", "models/sup/vrpm/104/eng/eng.mdl")
	AddPlayerModel("17", "models/sup/vrpm/104/hvy/hvy.mdl")
	AddPlayerModel("18", "models/sup/vrpm/104/ofc/ofc.mdl")
	AddPlayerModel("19", "models/sup/vrpm/104/recon/recon.mdl")
	AddPlayerModel("20", "models/sup/vrpm/104/sgt/sgt.mdl")
	AddPlayerModel("21", "models/sup/vrpm/104/support/support.mdl")
	AddPlayerModel("22", "models/sup/vrpm/104/trp/trp.mdl")
	AddPlayerModel("23", "models/sup/vrpm/15/ofc/ofc.mdl")
	AddPlayerModel("24", "models/sup/vrpm/15/sgt/sgt.mdl")
	AddPlayerModel("25", "models/sup/vrpm/15/trp/trp.mdl")
	AddPlayerModel("26", "models/sup/vrpm/327/arf/arf.mdl")
	AddPlayerModel("27", "models/sup/vrpm/327/eng/eng.mdl")
	AddPlayerModel("28", "models/sup/vrpm/327/ofc/ofc.mdl")
	AddPlayerModel("29", "models/sup/vrpm/327/pil/pil.mdl")
	AddPlayerModel("30", "models/sup/vrpm/327/pvt/pvt.mdl")
	AddPlayerModel("31", "models/sup/vrpm/327/sgt/sgt.mdl")
	AddPlayerModel("32", "models/sup/vrpm/327/trp/trp.mdl")
	AddPlayerModel("33", "models/sup/vrpm/327/para/para.mdl")
	AddPlayerModel("34", "models/sup/vrpm/327/pil/pil.mdl")
	AddPlayerModel("35", "models/sup/vrpm/501/desant/desant.mdl")
	AddPlayerModel("36", "models/sup/vrpm/501/driver/driver.mdl")
	AddPlayerModel("37", "models/sup/vrpm/501/hvy/hvy.mdl")
	AddPlayerModel("38", "models/sup/vrpm/501/ofc/ofc.mdl")
	AddPlayerModel("39", "models/sup/vrpm/501/recon/recon.mdl")
	AddPlayerModel("40", "models/sup/vrpm/501/sgt/sgt.mdl")
	AddPlayerModel("41", "models/sup/vrpm/501/support/support.mdl")
	AddPlayerModel("42", "models/sup/vrpm/501/trp/trp.mdl")
	AddPlayerModel("43", "models/sup/vrpm/8/arf/arf.mdl")
	AddPlayerModel("44", "models/sup/vrpm/8/hound/hound.mdl")
	AddPlayerModel("45", "models/sup/vrpm/8/ofc/ofc.mdl")
	AddPlayerModel("46", "models/sup/vrpm/8/sgt/sgt.mdl")
	AddPlayerModel("47", "models/sup/vrpm/8/trp/trp.mdl")
	AddPlayerModel("48", "models/sup/vrpm/8/arc/arc.mdl")
	AddPlayerModel("49", "models/sup/vrpm/501/arc/arc.mdl")
	AddPlayerModel("50", "models/sup/vrpm/327/arc/arc.mdl")
	AddPlayerModel("51", "models/sup/vrpm/212/arc/arc.mdl")
	AddPlayerModel("52", "models/sup/vrpm/104/arc/arc.mdl")
	AddPlayerModel("53", "models/sup/vrpm/8/hound/hound.mdl")
	AddPlayerModel("54", "models/sup/vrpm/501/arf/arf.mdl")
	AddPlayerModel("55", "models/sup/vrpm/327/arf/arf.mdl")
	AddPlayerModel("56", "models/sup/vrpm/212/arf/arf.mdl")
	AddPlayerModel("57", "models/sup/vrpm/104/arf/arf.mdl")
	AddPlayerModel("58", "models/sup/vrpm/1/hvy/hvy.mdl")
	AddPlayerModel("59", "models/sup/vrpm/1/desant/desant.mdl")
	AddPlayerModel("60", "models/sup/vrpm/1/support/support.mdl")
	AddPlayerModel("61", "models/sup/vrpm/arc/arc.mdl")
	AddPlayerModel("62", "models/sup/vrpm/arc/cmd/cmd.mdl")
	AddPlayerModel("63", "models/sup/vrpm/arc/cpt/cpt.mdl")
	AddPlayerModel("64", "models/sup/vrpm/arc/lt/lt.mdl")
	AddPlayerModel("65", "models/sup/vrpm/arc/sgt/sgt.mdl")
	AddPlayerModel("66", "models/sup/vrpm/kyramud/bastard/bastard.mdl")
	AddPlayerModel("67", "models/sup/vrpm/kyramud/pangolin/pangolin.mdl")
	AddPlayerModel("68", "models/sup/vrpm/kyramud/snake/snake.mdl")
	AddPlayerModel("69", "models/sup/vrpm/kyramud/tusk/tusk.mdl")
	AddPlayerModel("70", "models/sup/vrpm/kyramud/wouly/wouly.mdl")
	AddPlayerModel("71", "models/t_tcw_gar_alpha_wa/t_tcw_gar_alpha_wa.mdl")
	AddPlayerModel("72", "models/sup/vrpm/49/trp/trp.mdl")
	AddPlayerModel("73", "models/sup/vrpm/49/sgt/sgt.mdl")
	AddPlayerModel("74", "models/sup/vrpm/49/ofc/ofc.mdl")
	AddPlayerModel("75", "models/sup/vrpm/arf/pvt/pvt.mdl")
	AddPlayerModel("76", "models/sup/vrpm/arf/sgt/sgt.mdl")
	AddPlayerModel("77", "models/sup/vrpm/arf/cmd/cmd.mdl")
	AddPlayerModel("78", "models/sup/vrpm/arf/dcmd/dcmd.mdl")
	AddPlayerModel("79", "models/sup/vrpm/arf/ofc/ofc.mdl")
	AddPlayerModel("80", "models/aussiwozzi/cgi/commando/rc_boss.mdl")
	AddPlayerModel("81", "models/aussiwozzi/cgi/commando/rc_fixer.mdl")
	AddPlayerModel("82", "models/aussiwozzi/cgi/commando/rc_scorch.mdl")
	AddPlayerModel("83", "models/aussiwozzi/cgi/commando/rc_sev.mdl")
	AddPlayerModel("84", "models/aussiwozzi/cgi/commando/rc_aquila_batnor.mdl")
	AddPlayerModel("85", "models/aussiwozzi/cgi/commando/rc_aquila_cabur.mdl")
	AddPlayerModel("86", "models/aussiwozzi/cgi/commando/rc_aquila_cyarika.mdl")
	AddPlayerModel("87", "models/aussiwozzi/cgi/commando/rc_aquila_monarch.mdl")
	AddPlayerModel("88", "models/aussiwozzi/cgi/commando/rc_aquila_monarch.mdl")
	AddPlayerModel("89", "models/aussiwozzi/cgi/commando/rc_corr.mdl")
	AddPlayerModel("90", "models/aussiwozzi/cgi/commando/rc_darman.mdl")
	AddPlayerModel("91", "models/aussiwozzi/cgi/commando/rc_fi.mdl")
	AddPlayerModel("92", "models/aussiwozzi/cgi/commando/rc_dikut.mdl")
	AddPlayerModel("93", "models/aussiwozzi/cgi/commando/rc_fisher.mdl")
	AddPlayerModel("94", "models/aussiwozzi/cgi/commando/rc_foxtrot_demo.mdl")
	AddPlayerModel("95", "models/aussiwozzi/cgi/commando/rc_foxtrot_sniper.mdl")
	AddPlayerModel("96", "models/aussiwozzi/cgi/commando/rc_foxtrot_tech.mdl")
	AddPlayerModel("97", "models/aussiwozzi/cgi/commando/rc_gregor.mdl")
	AddPlayerModel("98", "models/aussiwozzi/cgi/commando/rc_hope_demo.mdl")
	AddPlayerModel("99", "models/aussiwozzi/cgi/commando/rc_hope_leader.mdl")
	AddPlayerModel("100", "models/aussiwozzi/cgi/commando/rc_hope_sniper.mdl")
	AddPlayerModel("101", "models/aussiwozzi/cgi/commando/rc_hope_tech.mdl")
	AddPlayerModel("102", "models/aussiwozzi/cgi/commando/rc_ion_climber.mdl")
	AddPlayerModel("103", "models/aussiwozzi/cgi/commando/rc_ion_ras.mdl")
	AddPlayerModel("104", "models/aussiwozzi/cgi/commando/rc_ion_sniper.mdl")
	AddPlayerModel("105", "models/aussiwozzi/cgi/commando/rc_ion_trace.mdl")
	AddPlayerModel("106", "models/aussiwozzi/cgi/commando/rc_niner.mdl")
	AddPlayerModel("107", "models/aussiwozzi/cgi/commando/rc_plain.mdl")
	AddPlayerModel("108", "models/aussiwozzi/cgi/commando/rc_sarge.mdl")
	AddPlayerModel("109", "models/aussiwozzi/cgi/commando/rc_tyto.mdl")
	AddPlayerModel("110", "models/aussiwozzi/cgi/commando/rc_yayax_cov.mdl")
	AddPlayerModel("111", "models/aussiwozzi/cgi/commando/rc_yayax_dev.mdl")
	AddPlayerModel("112", "models/aussiwozzi/cgi/commando/rc_yayax_jind.mdl")
	AddPlayerModel("113", "models/aussiwozzi/cgi/commando/rc_yayax_yover.mdl")
	AddPlayerModel("114", "models/aussiwozzi/cgi/commando/rc_zag.mdl")
	AddPlayerModel("115", "models/aussiwozzi/cgi/commando/rc_plain.mdl")
	AddPlayerModel("116", "models/aussiwozzi/cgi/commando/rc_snow.mdl")
	AddPlayerModel("117", "models/aussiwozzi/cgi/commando/rc_forest.mdl")
	AddPlayerModel("118", "models/sup/vrpm/187/trp/trp.mdl")
	AddPlayerModel("119", "models/sup/vrpm/187/sgt/sgt.mdl")
	AddPlayerModel("120", "models/sup/vrpm/212/cody/cody.mdl")
	AddPlayerModel("121", "models/sup/vrpm/212/desant/desant.mdl")
	AddPlayerModel("122", "models/sup/vrpm/212/eng/eng.mdl")
	AddPlayerModel("123", "models/sup/vrpm/212/hvy/hvy.mdl")
	AddPlayerModel("124", "models/sup/vrpm/212/ofc/ofc.mdl")
	AddPlayerModel("125", "models/sup/vrpm/212/recon/recon.mdl")
	AddPlayerModel("126", "models/sup/vrpm/212/sgt/sgt.mdl")
	AddPlayerModel("127", "models/sup/vrpm/212/trp/trp.mdl")
	AddPlayerModel("128", "models/sup/vrpm/187/ofc/ofc.mdl")
	AddPlayerModel("130", "models/sup/vrpm/8/cmd/cmd.mdl")
	AddPlayerModel("131", "models/sup/vrpm/8/driver/driver.mdl")
	AddPlayerModel("132", "models/sup/vrpm/8/eng/eng.mdl")
	AddPlayerModel("133", "models/sup/vrpm/8/hvy/hvy.mdl")
	AddPlayerModel("134", "models/sup/vrpm/8/recon/recon.mdl")
	AddPlayerModel("135", "models/sup/vrpm/8/support/support.mdl")
	AddPlayerModel("136", "models/sup/vrpm/arf/xanter/xanter.mdl")
	AddPlayerModel("137", "models/aussiwozzi/cgi/commando/rc_desert.mdl")
	AddPlayerModel("138", "models/sup/vrpm/104/driver/driver.mdl")


	player_manager.AddValidHands("1", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("2", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("3", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("4", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("5", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("6", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("7", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("8", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("9", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("10", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("11", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("12", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("13", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("14", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("15", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("16", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("17", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("18", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("19", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("20", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("21", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("22", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("23", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("24", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("25", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("26", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("27", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("28", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("29", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("30", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("31", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("32", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("33", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("34", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("35", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("36", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("37", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("38", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("39", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("40", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("41", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("42", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("43", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("44", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("45", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("46", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("47", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("48", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("49", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("50", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("51", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("52", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("53", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("54", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("55", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("56", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("57", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("58", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("59", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("60", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("61", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("62", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("63", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("64", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("65", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("66", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("67", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("68", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("69", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("70", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("71", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("72", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("73", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("74", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("75", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("76", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("77", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("78", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("79", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("80", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("81", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("82", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("83", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("84", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("85", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("86", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("87", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("88", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("89", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("90", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("91", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("92", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("93", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("94", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("95", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("96", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("97", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("98", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("99", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("100", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("101", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("102", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("103", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("104", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("105", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("106", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("107", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("108", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("109", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("110", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("111", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("112", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("113", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("114", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("115", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("116", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("117", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("118", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("119", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("120", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("121", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("122", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("123", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("124", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("125", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("126", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("127", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("128", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("129", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("130", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("131", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("132", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("133", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("134", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("135", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("136", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	player_manager.AddValidHands("137", "models/aussiwozzi/cgi/commando/commando_arms.mdl", 0, "10000000")
	player_manager.AddValidHands("138", "models/galactic/clones/clonearms.mdl", 0, "10000000")
	




end)
-- hook.Add("PlayerSay", "NPCIgnorePlayer", function(ply, text)
--     if ply:IsSuperAdmin() and text == "/npctarget" or "!npctarget" then
--         ply.NPCVisible = not ply.NPCVisible
--         local newDisposition = ply.NPCVisible and D_HT or D_LI
--         local npcs = ents.FindByClass("npc_*")
--         for _, npc in ipairs(npcs) do
--             if npc:IsNPC() then
--                 npc:AddEntityRelationship(ply, newDisposition, 99)
--             end
--         end
--         if ply.NPCVisible then
--             ply:ChatPrint("Вы снова видимы для NPC.")
--         else
--             ply:ChatPrint("Вы теперь невидимы для NPC.")
--         end
--         return ""
--     end
-- end)
-- if SERVER then
--     concommand.Add("cleanupmap", function(ply, cmd, args)
--         if ply:IsSuperAdmin() then
--             game.CleanUpMap()
--             ply:ChatPrint("[CleanUpMap] Карта успешно очищена.")
--         else
--             ply:ChatPrint("[CleanUpMap] Для выполнения этой команды вы должны быть супер-администратором.")
--         end
--     end)
-- end

--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher
