--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher

game.AddParticles( "particles/astw2_halo_flamethrower.pcf" )
-- game.AddParticles( "particles/gravity_hammer_fx.pcf" )
game.AddParticles( "particles/iv04_halo_reach_gravity_hammer_effects.pcf" )
game.AddParticles( "particles/iv04_halo_reach_explosions.pcf" )
game.AddParticles( "particles/astw2_halo_pack_muzzle_effects.pcf" )
game.AddParticles( "particles/astw2_halo_pack_muzzle_effects2.pcf" )
game.AddParticles( "particles/astw2_halo_pack_muzzle_effects_human_spv3.pcf" )
game.AddParticles( "particles/astw2_halo_pack_muzzle_effects_covie_spv3.pcf" )
game.AddParticles( "particles/astw2_halo_pack_weapon_projectiles.pcf" )
game.AddParticles( "particles/astw2_gravity_hammer_fx.pcf" )
game.AddParticles( "particles/astw2_halo_pack_explosions.pcf" )
game.AddParticles( "particles/simfphys_halo_muzzle_effects.pcf" )
game.AddParticles( "particles/astw2_halo_4_forerunner_fx.pcf" )
game.AddParticles( "particles/astw2_halo_3_equipment_fx.pcf" )
game.AddParticles( "particles/astw2_halo_3_equipment_explosion_fx.pcf" )

--CASING EFFECTS
PrecacheParticleSystem( "astw2_halo_ce_casing_pistol" )
PrecacheParticleSystem( "astw2_halo_ce_casing_rifle" )
PrecacheParticleSystem( "astw2_halo_ce_casing_sniper" )
PrecacheParticleSystem( "astw2_halo_ce_casing_shotgun" )

--EQUIPMENT STUFF
PrecacheParticleSystem( "astw2_halo_3_bubbleshield_fx" )
PrecacheParticleSystem( "astw2_halo_3_power_drain_fx" )
PrecacheParticleSystem( "astw2_halo_3_power_drain_explosion_fx" )
PrecacheParticleSystem( "astw2_halo_3_deployable_cover_shield_deplete_fx" )
PrecacheParticleSystem( "astw2_halo_3_deployable_cover_impact_fx" )
PrecacheParticleSystem( "astw2_halo_3_deployable_cover_explosion_fx" )
PrecacheParticleSystem( "astw2_halo_3_deployable_shield_depleted_fx" )
PrecacheParticleSystem( "astw2_halo_3_invincibility_fx" )
PrecacheParticleSystem( "astw2_halo_3_invincibility_pickup_fx" )
PrecacheParticleSystem( "astw2_halo_3_invincibility_pickup_fx_flare" )
PrecacheParticleSystem( "astw2_halo_3_invincibility_pickup_fx_vapor" )
PrecacheParticleSystem( "astw2_halo_3_invisibility_pickup_fx" )
PrecacheParticleSystem( "astw2_halo_3_invisibility_pickup_fx_flare" )
PrecacheParticleSystem( "astw2_halo_3_invisibility_pickup_fx_vapor" )
PrecacheParticleSystem( "astw2_halo_3_gravlift_fx" )
PrecacheParticleSystem( "astw2_halo_3_superflare_fx" )
PrecacheParticleSystem( "astw2_halo_3_regenerator_fx" )
PrecacheParticleSystem( "astw2_halo_3_regenerator_explosion_fx" )
PrecacheParticleSystem( "astw2_halo_3_flamethrower_pilot_fx" )
PrecacheParticleSystem( "astw2_halo_3_hammer_fx" )
PrecacheParticleSystem( "astw2_halo_3_hammer_fx_current" )
PrecacheParticleSystem( "astw2_halo_3_sword_fx" )

--Projectile Effects
PrecacheParticleSystem( "astw2_halo_ce_plasma_grenade_trail" )
PrecacheParticleSystem( "astw2_halo_ce_rocket_launcher_trail" )
PrecacheParticleSystem( "astw2_halo_ce_fuel_rod_trail" )
PrecacheParticleSystem( "astw2_halo_2_sentinel_beam_tracer" )
PrecacheParticleSystem( "astw2_halo_2_sentinel_beam_blue_tracer" )
PrecacheParticleSystem( "astw2_halo_2_needler_trail" )
PrecacheParticleSystem( "astw2_halo_2_enforcer_needler_trail" )
PrecacheParticleSystem( "astw2_halo_2_brute_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_2_fuel_rod_projectile_trail" )
PrecacheParticleSystem( "astw2_halo_2_plasma_grenade_trail" )
PrecacheParticleSystem( "astw2_halo_2_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_2_plasma_pistol_trail" )
PrecacheParticleSystem( "astw2_halo_3_brute_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_3_plasma_grenade_trail" )
PrecacheParticleSystem( "astw2_halo_3_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_3_plasma_pistol_trail" )
PrecacheParticleSystem( "astw2_halo_3_plasma_pistol_overcharge_trail" )
PrecacheParticleSystem( "astw2_halo_3_needler_trail" )
PrecacheParticleSystem( "astw2_halo_3_frag_grenade_trail" )
PrecacheParticleSystem( "astw2_halo_3_rocket_launcher_trail" )
PrecacheParticleSystem( "astw2_halo_3_spiker_trail" )
PrecacheParticleSystem( "astw2_halo_3_flood_ranged_form_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_brute_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_brute_plasma_pistol_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_plasma_rifle_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_plasma_pistol_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_plasma_pistol_overcharge_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_brute_plasma_pistol_overcharge_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_shredder_trail" )
PrecacheParticleSystem( "astw2_halo_spv3_spiker_trail" )
PrecacheParticleSystem( "astw2_halo_reach_concussion_round_trail" )
PrecacheParticleSystem( "astw2_halo_reach_grenade_launcher_trail" )
PrecacheParticleSystem( "astw2_halo_3_nuke_launcher_trail" )
PrecacheParticleSystem( "astw2_halo_aerial_dark_projectile_trail" )
PrecacheParticleSystem( "astw2_halo_phantom_projectile_fx" )
PrecacheParticleSystem( "astw2_halo_2_impact_brute_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_2_impact_carbine" )
PrecacheParticleSystem( "astw2_halo_2_impact_needler" )
PrecacheParticleSystem( "astw2_halo_2_impact_plasma_rifle" )
--Misc Effects
PrecacheParticleSystem( "flame_halo_3" )
PrecacheParticleSystem( "astw2_halo_3_gravity_hammer_fx" )
--Explosion Effects
PrecacheParticleSystem( "halo_reach_explosion_unsc" )
PrecacheParticleSystem( "halo_reach_explosion_covenant" )
PrecacheParticleSystem( "halo_reach_gravity_hammer_smash" )
PrecacheParticleSystem( "astw2_halo_2_brute_shot_explosion" )
PrecacheParticleSystem( "astw2_halo_2_frag_explosion" )
PrecacheParticleSystem( "astw2_halo_2_mortar_explosion" )
PrecacheParticleSystem( "astw2_halo_2_rocket_explosion" )
PrecacheParticleSystem( "astw2_halo_2_overcharge_impact" )
PrecacheParticleSystem( "astw2_halo_2_fuel_rod_explosion" )
PrecacheParticleSystem( "astw2_halo_2_needler_explosion" )
PrecacheParticleSystem( "astw2_halo_2_plasma_explosion" )
PrecacheParticleSystem( "astw2_halo_3_brute_shot_explosion" )
PrecacheParticleSystem( "astw2_halo_3_firebomb_explosion" )
PrecacheParticleSystem( "astw2_halo_3_frag_explosion" )
PrecacheParticleSystem( "astw2_halo_3_overcharge_impact" )
PrecacheParticleSystem( "astw2_halo_3_fuel_rod_explosion" )
PrecacheParticleSystem( "astw2_halo_3_needler_explosion" )
PrecacheParticleSystem( "astw2_halo_3_plasma_explosion" )
PrecacheParticleSystem( "astw2_halo_3_rocket_explosion" )
PrecacheParticleSystem( "astw2_halo_3_spike_grenade_explosion" )
PrecacheParticleSystem( "astw2_halo_3_hunter_projectile_impact" )
PrecacheParticleSystem( "astw2_halo_spv3_hunter_projectile_impact" )
PrecacheParticleSystem( "astw2_halo_ce_sml_explosion" )
PrecacheParticleSystem( "astw2_halo_ce_frag_explosion" )
PrecacheParticleSystem( "astw2_halo_ce_needler_explosion" )
PrecacheParticleSystem( "astw2_halo_ce_plasma_explosion" )
PrecacheParticleSystem( "astw2_halo_reach_concussion_rifle_explosion" )
PrecacheParticleSystem( "astw2_halo_reach_fuel_rod_explosion" )
PrecacheParticleSystem( "astw2_halo_reach_needler_explosion" )
PrecacheParticleSystem( "astw2_halo_reach_plasma_explosion" )
PrecacheParticleSystem( "astw2_halo_custom_mac_explosion" )
PrecacheParticleSystem( "astw2_halo_custom_nuke_explosion_XXL" )
PrecacheParticleSystem( "astw2_halo_custom_nuke_explosion_huge" )
PrecacheParticleSystem( "astw2_halo_phantom_projectile_impact_fx" )
PrecacheParticleSystem( "astw2_halo_2_sentinel_impact_blue" )
PrecacheParticleSystem( "astw2_halo_2_sentinel_impact_red" )
--Muzzle Effects
PrecacheParticleSystem( "astw2_halo_aerial_muzzle_dark_carbine" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_turret_covenant" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_beam_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_brute_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_brute_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_brute_shot" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_carbine" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_focus_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_fuel_rod" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_mauler" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_needler" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_particle_carbine" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_shredder" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_spiker" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_assault_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_battle_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_DMR" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_magnum" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_shotgun" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_SMG" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_SMG_specops" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_sniper_rifle" )
PrecacheParticleSystem( "astw2_halo_spv3_muzzle_sniper_rifle_specops" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_gravity_wrench_charge" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_assault_rifle" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_pistol" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_shotgun" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_sniper_rifle" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_fuel_rod" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_ce_muzzle_needler" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_battle_rifle" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_SMG" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_sniper_rifle" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_shotgun" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_rocket_launcher" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_magnum" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_brute_shot" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_carbine" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_beam_rifle" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_brute_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_fuel_rod" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_needler" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_sentinel_beam_red" )
PrecacheParticleSystem( "astw2_halo_2_muzzle_sentinel_beam_blue" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_assault_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_battle_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_hunter_cannon_charge" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_magnum" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_magnum_ODST" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_SMG" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_SMG_ODST" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_rocket_launcher" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_sniper_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_shotgun" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_machine_gun_turret" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_missile_pod" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_spartan_laser" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_spartan_laser_charge" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_carbine" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_brute_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_plasma_turret" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_fuel_rod" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_needler" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_spiker" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_brute_shot" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_mauler" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_mauler_flare" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_nuke_flare" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_laser_painter_flare" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_laser_painter_blue_flare" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_beam_rifle" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_warthog_chaingun" )
PrecacheParticleSystem( "astw2_halo_3_muzzle_warthog_gauss_cannon" )
PrecacheParticleSystem( "astw2_halo_4_muzzle_forerunner_aiming_beam" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_assault_rifle" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_DMR" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_magnum" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_sniper_rifle" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_plasma_repeater" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_plasma_pistol" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_plasma_rifle" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_focus_rifle" )
PrecacheParticleSystem( "astw2_halo_reach_muzzle_concussion_rifle" )
PrecacheParticleSystem( "astw2_halo_reach_focus_rifle_impact" )
PrecacheParticleSystem( "astw2_halo_3_sentinel_impact_blue" )
PrecacheParticleSystem( "astw2_halo_3_sentinel_impact_red" )
PrecacheParticleSystem( "astw2_halo_3_laser_beam_blue" )
PrecacheParticleSystem( "astw2_halo_3_laser_beam_red" )
PrecacheParticleSystem( "astw2_halo_3_laser_beam_monitor" )
PrecacheParticleSystem( "simphys_halo_warthog_gauss_muzzle" )
--Decal Effects
game.AddDecal( "astw2_halo_reach_impact_nuke_explosion", "effects/halo_reach/impact_nuke_explosion" )
game.AddDecal( "astw2_halo_reach_impact_soft_terrain_explosion", "effects/halo_reach/impact_soft_terrain_explosion" )
game.AddDecal( "astw2_halo_reach_impact_hard", "effects/halo_reach/impact_hard" )
game.AddDecal( "astw2_halo_reach_impact_hard_medium", "effects/halo_reach/impact_hard_medium" )
game.AddDecal( "astw2_halo_3_sword_impact_medium", "effects/halo3/sword_impact_medium" )
game.AddDecal( "astw2_halo_3_impact_gauss", "effects/halo3/blast_scorch_ring" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_blue", "effects/halo3/plasma_impact_medium_blue" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_blue_sentinel", "effects/halo3/plasma_impact_medium_blue_sentinel" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_red", "effects/halo3/plasma_impact_medium_red" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_red_laser", "effects/halo3/plasma_impact_medium_red_laser" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_green", "effects/halo3/plasma_impact_medium_green" )
game.AddDecal( "astw2_halo_3_plasma_impact_medium_green_carbine", "effects/halo3/plasma_impact_medium_green_carbine" )
game.AddDecal( "astw2_halo_3_plasma_impact_large_purple", "effects/halo3/plasma_impact_large_purple" )
game.AddDecal( "astw2_halo_3_plasma_impact_large_green", "effects/halo3/plasma_impact_large_green" )
game.AddDecal( "astw2_halo_3_napalm_splat_large", "effects/halo3/napalm_splat_large1" )
game.AddDecal( "astw2_halo_3_blast_scorch_large", "effects/halo3/blast_scorch_large" )
game.AddDecal( "astw2_halo_2_phantom_plasma_burn", "effects/halo2/phantom_plasma_burn" )
game.AddDecal( "astw2_halo_2_plasma_burn_inner_glow", "effects/halo2/plasma_burn_inner_glow" )
game.AddDecal( "astw2_halo_2_plasma_blue_fizzle", "effects/halo2/plasma_blue_fizzle" )
game.AddDecal( "astw2_halo_2_plasma_blue_glow", "effects/halo2/plasma_blue_glow" )
game.AddDecal( "astw2_halo_2_plasma_burn_inner_glow_brute", "effects/halo2/plasma_burn_inner_glow_brute" )
game.AddDecal( "astw2_halo_2_plasma_red_glow", "effects/halo2/plasma_red_glow" )
game.AddDecal( "astw2_halo_2_plasma_red_fizzle", "effects/halo2/plasma_red_fizzle" )
game.AddDecal( "astw2_halo_2_plasma_explosion_glow_inner", "effects/halo2/plasma_explosion_glow_inner" )
game.AddDecal( "astw2_halo_2_plasma_beam_rifle_glow", "effects/halo2/beam_rifle_glow" )
game.AddDecal( "astw2_halo_2_plasma_green_inner_glow", "effects/halo2/plasma_green_inner_glow" )
game.AddDecal( "astw2_halo_2_plasma_green_glow", "effects/halo2/plasma_green_glow" )
game.AddDecal( "astw2_halo_2_plasma_green_fizzle", "effects/halo2/plasma_green_fizzle" )
game.AddDecal( "astw2_halo_2_default_scorch", "effects/halo2/default_scorch" )
game.AddDecal( "astw2_halo_2_default_blast", "effects/halo2/default_blast" ) 
game.AddParticles( "particles/swbf/astw2_swbf_explosions.pcf" )
game.AddParticles( "particles/swbf/astw2_star_wars_battlefront_muzzle_effects.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_flamethrower.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_rocket_fx.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_impact_fx.pcf" )
game.AddParticles( "particles/swbf/astw2_swbf_pickup_effects.pcf" )
game.AddParticles( "particles/swbf/swbf_commandpost_fx.pcf" )
PrecacheParticleSystem( "astw2_swbf_explosion_cis_launcher" )
PrecacheParticleSystem( "astw2_swbf_explosion_cis_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_cis_wristrocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_concussion_grenade" )
PrecacheParticleSystem( "astw2_swbf_explosion_emp" )
PrecacheParticleSystem( "astw2_swbf_explosion_imp_launcher" )
PrecacheParticleSystem( "astw2_swbf_explosion_imp_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_reb_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_rep_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_thermal_detonator" )
PrecacheParticleSystem( "astw2_swbf_explosion_thermal_detonator2" )
PrecacheParticleSystem( "astw2_swbf_explosion_rep_emp_rocket" )
PrecacheParticleSystem( "astw2_swbf_explosion_death_droid" )
PrecacheParticleSystem( "astw2_swbf_muzzle_tor_rifle" )
PrecacheParticleSystem( "astw2_swbf_muzzle_sth_rifle" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_cis_bulldog" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_shotgun" )
PrecacheParticleSystem( "astw2_swbf_muzzle_imp_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_shotgun" )
PrecacheParticleSystem( "astw2_swbf_muzzle_reb_bowcaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_blaster" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_pistol" )
PrecacheParticleSystem( "astw2_swbf_muzzle_rep_sniper" )
PrecacheParticleSystem( "astw2_swbf_muzzle_tus_rifle" )
PrecacheParticleSystem( "astw2_swbf_flamethrower_fx" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_generic" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_all" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_cis" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_imp" )
PrecacheParticleSystem( "astw2_swbf_rocket_fx_rep" )
PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact" )
PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact_yellow" )
PrecacheParticleSystem( "astw2_swbf_blaster_bolt_impact_heavy" )
PrecacheParticleSystem( "astw2_swbf_pickup_ammo" )
PrecacheParticleSystem( "astw2_swbf_pickup_bacta" )
PrecacheParticleSystem( "astw2_swbf_pickup_dual" )
PrecacheParticleSystem( "astw2_swbf_pickup_energy" )
PrecacheParticleSystem( "astw2_swbf_pickup_rage" )
PrecacheParticleSystem( "astw2_swbf_pickup_rally" )
PrecacheParticleSystem( "swbf_command_post_ally" )
PrecacheParticleSystem( "swbf_command_post_friendly" )
PrecacheParticleSystem( "swbf_command_post_enemy" )
PrecacheParticleSystem( "swbf_command_post_neutral" )
PrecacheParticleSystem( "swbf_command_post_unoccupied" )




--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher
